CREATE 
  (`0` :PreRunSetup {prepDuration:'Time',lotNumber:'String',location:'String',productSKU:'String'}),
  (`1` :PostRunStage {postDuration:'Time',lotNumber:'String',location:'String',productSKU:'String'}),
  (`2` :Employee {location:'String',gender:'String',email:'String',lastName:'String',firstName:'String',employeeID:'Integer'}),
  (`3` :ProductionRun {finishTime:'LocalTime',startTime:'LocalTime',runTimeHMS:'LocalTime',runDuration:'Duration',lotNumber:'Integer',location:'String',productSKU:'String'}),
  (`4` :Equipment {location:'String',step:'Integer',stage:'Integer',serialNumber:'String',model:'String',nomenclature:'String',manufacturer:'String',equipID:'Integer'}),
  (`5` :Batch {setupTime:'Time',nextStepWaitTme:'Time',qcHoldTime:'Time',productionTime:'Time',package:'String',strength:'String',form:'String',generation:'String',dateProduced:'Date',lotNumber:'String',productSKU:'String',materialType:'String',location:'String',globalBrand:'String'}),
  (`6` :ProcessStep {package:'String',processStep:'String',isLastStep:'Boolean',stepNum:'Integer',materialType:'String',stageNum:'Integer',nextStep:'Integer',nextStage:'Integer',process:'String',processStage:'String',globalBrand:'String',location:'String'}),
  (`7` :Product:API:DIST:RM:FG:DP:BULK {package:'String',strength:'String',location:'String',materialType:'String',globalBrand:'String',rmSequence:'Integer',generation:'String',form:'String',description:'String',productSKU:'String'}),
  (`8` :Recipe {market:'String',stepList:'String',productList:'String',globalBrand:'String',stageList:'String',form:'String',molecularForm:'String',generation:'String',materialList:'String',strength:'String'}),
  (`9` :ProcessStage {process:'String',location:'String',nextStage:'Integer',processStage:'String',materialType:'String',stageNum:'Integer',globalBrand:'String'}),
  (`10` :MaterialType {materialType:'String',location:'String',globalBrand:'String'}),
  (`11` :GlobalBrand {molecularForm:'String',globalBrand:'String'}),
  (`12` :Suppliers {countryCode:'String',companyName:'String'}),
  (`13` :Distributor {market:'String',location:'String'}),
  (`14` :ProcessTemplates {addRM:'Boolean',package:'String',nextStage:'Integer',stepName:'String',stageName:'String',stage:'Integer',isLastStep:'Boolean',step:'Integer',process:'String',materialType:'String',nextStep:'Integer',forkBefore:'Boolean'}),
  (`15` :Site {location:'String',market:'String'}),
  (`6`)-[:IS_STEP_IN ]->(`9`),
  (`5`)-[:NEXT_EQUIP_BATCH ]->(`5`),
  (`1`)-[:NEXT_EQUIP_USE ]->(`0`),
  (`4`)-[:USED_FOR_BATCH ]->(`5`),
  (`4`)-[:FIRST_RUN_EQUIP ]->(`3`),
  (`5`)-[:BATCH_FLOW ]->(`13`),
  (`12`)-[:SUPPLIES_BATCH ]->(`5`),
  (`1`)-[:EQUIP_POSTRUN ]->(`4`),
  (`0`)-[:EQUIP_SETUP ]->(`4`),
  (`3`)-[:NEXT_RUN_SAME_OPER ]->(`3`),
  (`3`)-[:NEXT_RUN_EQUIP {idleDuration:'Duration'}]->(`3`),
  (`2`)-[:PERFORMED_POSTRUN ]->(`1`),
  (`0`)-[:PERFORMED_SETUP ]->(`2`),
  (`0`)-[:PREP_FOR_RUN ]->(`3`),
  (`3`)-[:POSTRUN ]->(`1`),
  (`2`)-[:IS_CERTIFIED_OPERATOR {yearsExperience:'Integer'}]->(`4`),
  (`3`)-[:PRODUCED_BATCH ]->(`5`),
  (`3`)-[:USED_EQUIP ]->(`4`),
  (`2`)-[:PERFORMED_RUN ]->(`3`),
  (`6`)-[:PROCESSING_EQUIPMENT ]->(`4`),
  (`5`)-[:BATCH_FLOW {lotNumber:'String',strength:'String',form:'String',generation:'String',market:'String',globalBrand:'String'}]->(`5`),
  (`5`)-[:IS_BATCH_FOR ]->(`7`),
  (`7`)-[:CONSUMES ]->(`6`),
  (`8`)-[:STAGE_FLOW {strength:'String',form:'String',market:'String',generation:'String',globalBrand:'String'}]->(`9`),
  (`9`)-[:IS_STAGE_IN ]->(`10`),
  (`14`)-[:NEXT_TEMPLATE_STEP ]->(`14`),
  (`10`)-[:MATERIAL_FLOW {market:'String',generation:'String',form:'String',strength:'String',globalBrand:'String'}]->(`10`),
  (`8`)-[:MATERIAL_FLOW {market:'String',strength:'String',globalBrand:'String',form:'String',generation:'String'}]->(`10`),
  (`8`)-[:STEP_FLOW {globalBrand:'String',generation:'String',strength:'String',market:'String',form:'String'}]->(`6`),
  (`7`)-[:PRODUCT_FLOW {package:'String',globalBrand:'String',strength:'String',conversionRatio:'Float',market:'String',generation:'String',form:'String'}]->(`7`),
  (`14`)-[:NEXT_TEMPLATE_STEP ]->(`14`),
  (`8`)-[:PRODUCT_FLOW {form:'String',globalBrand:'String',strength:'String',generation:'String',market:'String',conversionRatio:'Float'}]->(`7`),
  (`6`)-[:STEP_FLOW {globalBrand:'String',strength:'String',form:'String',generation:'String',market:'String'}]->(`6`),
  (`11`)-[:HAS_RECIPE ]->(`8`),
  (`12`)-[:SUPPLIES_RM {supplierCapacity:'Integer'}]->(`7`),
  (`7`)-[:DISTRIBUTED_BY {demandQty:'Integer'}]->(`13`),
  (`9`)-[:STAGE_FLOW {form:'String',generation:'String',globalBrand:'String',market:'String',strength:'String'}]->(`9`),
  (`6`)-[:PRODUCES ]->(`7`)